development:
  :concurrency: 4
production:
  :concurrency: 2
:queues:
  - default
:dynamic: true
:schedule:    
  CheckMonikerWorker:
    every: ["30m"]
  DestroyNotifyLogsWorker:
    cron: 0 23 * * *
    class: DestroyNotifyLogsWorker
